import type { Metadata } from "next";
import { Catamaran, Castoro_Titling } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const catamaran = Catamaran({
  variable: "--font-catamaran",
  subsets: ["latin"],
});

const castoroTitling = Castoro_Titling({
  variable: "--font-castoro-titling",
  subsets: ["latin"],
  weight: ['400']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${catamaran.variable} ${castoroTitling.variable} antialiased`}
      >
        {children}
        <Footer/>
      </body>
    </html>
  );
}
